export const plans = [
  {
    id: "basic",
    name: "Basic Plan",
    price: 99,
    interval: "month",
    visits: "3 visits",
    extraVisit: "$40 for extra",
    services: ["ADLs", "Light housekeeping", "Medication reminders"],
    description: "Perfect for those needing occasional assistance",
    priceId: "price_1Qq12LGBXcslzN0XTElvUvoQ",
  },
  {
    id: "premium",
    name: "Premium Plan",
    price: 199,
    interval: "month",
    visits: "6 visits",
    extraVisit: "$35 for extra",
    services: ["ADLs", "Medication management", "Basic health assessments"],
    description: "Ideal for regular care needs",
    popular: true,
    priceId: "price_1Qq13BGBXcslzN0XZdx0xBYW",
  },
  {
    id: "unlimited",
    name: "Unlimited Plan",
    price: 399,
    interval: "month",
    visits: "Unlimited",
    extraVisit: null,
    services: ["All services within reasonable usage (e.g., 4 visits/week)"],
    description: "Complete coverage for comprehensive care",
    priceId: "price_1Qq141GBXcslzN0XzJZfZqR2",
  },
  {
    id: "cna-visit",
    name: "CNA Visit",
    price: 60,
    interval: "visit",
    visits: "One-time",
    extraVisit: null,
    services: ["ADLs", "Companionship (up to 2 hours)"],
    description: "Flexible, on-demand care when you need it",
    perVisit: true,
    priceId: "price_1Qq14eGBXcslzN0X6I0XkCp9",
  },
]